# Generated by Django 5.1.4 on 2024-12-30 17:50

from django.utils import timezone
from django.db import migrations
import os
from dotenv import load_dotenv

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    def create_superuser(apps, schema_editor):
        from django.contrib.auth import get_user_model

        User = get_user_model()

        if User.objects.exists():
            return

        load_dotenv()

        superuser = User.objects.create_superuser(
            username=os.getenv("SUPERUSER_USERNAME"),
            email=os.getenv("SUPERUSER_EMAIL"),
            password=os.getenv("SUPERUSER_PASSWORD"),
            last_login=timezone.now()
        )
        superuser.save()

    operations = [
        migrations.RunPython(create_superuser),
    ]
